### ISSUE TITLE
Inizializzazione App: non carica i dati

### ISSUE THREAD

**Issue by maxvaega** [giammaleoni/TestPBo#7]
# Inizializzazione App: non carica i dati

testato su PC, dopo aver pulito la cache: 
![image](https://cloud.githubusercontent.com/assets/12343497/8317934/3da6ece6-1a01-11e5-9873-e25fe50e75a3.png)

succede che l'app rimane cosi:
![image](https://cloud.githubusercontent.com/assets/12343497/8317947/55534628-1a01-11e5-9e7c-efd590ecac98.png)

andando nei settings, si trovano cosi:
![image](https://cloud.githubusercontent.com/assets/12343497/8317955/61f925d2-1a01-11e5-86d5-423449fc06da.png)

in console si vede: 
![image](https://cloud.githubusercontent.com/assets/12343497/8318040/dc706000-1a01-11e5-9bcb-00defe981193.png)

sembra ci sia un errore nelle modalità di esecuzione di recuperaIlDato(): probabilmente c'è qualcosa che si pianta perchè non trova il dato (già l'avevo fixato per la dropdown del marker c'era questo problema)
- [x] Fixed

**Comment by giammaleoni** [comment]
A me non da questo errore. A te continua a dartelo?

**Comment by giammaleoni** [comment]
Ho provato cancellando anche i dati host ma va tutto benissimo

**Comment by maxvaega** [comment]
Sono una fava, è la cosa che avevo fixato l'altra sera. solo che l'avevo
fatto dal computer fisso :D FAVELAS :D :D
Ora faccio un po di angular su fiddle.................. ;)

Il giorno mer 24 giu 2015 alle ore 08:49 Gianmaria Leoni <
notifications@github.com> ha scritto:

**Comment by maxvaega** [comment]
risolto
